apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: strimzi-drain-cleaner
  labels:
    helm.sh/chart: strimzi-drain-cleaner-0.0.3
    app.kubernetes.io/name: strimzi-drain-cleaner
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.3.1"
    app.kubernetes.io/managed-by: Helm
spec:
  secretName: strimzi-drain-cleaner
  commonName: strimzi-drain-cleaner
  dnsNames:
    - strimzi-drain-cleaner.strimzi-drain-cleaner.svc
    - strimzi-drain-cleaner.strimzi-drain-cleaner
    - strimzi-drain-cleaner
  issuerRef:
    name: strimzi-drain-cleaner
