apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-drain-cleaner
  labels:
    helm.sh/chart: strimzi-drain-cleaner-0.0.3
    app.kubernetes.io/name: strimzi-drain-cleaner
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.3.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: strimzi-drain-cleaner
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: strimzi-drain-cleaner
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: release-name-strimzi-drain-cleaner
      containers:
        - name: strimzi-drain-cleaner
          image: quay.io/strimzi/drain-cleaner:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8443
              name: https
          env:
            - name: STRIMZI_DRAIN_KAFKA
              value: "true"
            - name: STRIMZI_DRAIN_ZOOKEEPER
              value: "true"
          args:
            - /opt/strimzi/bin/drain_cleaner_run.sh
          volumeMounts:
            - name: webhook-certificates
              mountPath: "/etc/webhook-certificates"
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
      volumes:
        - name: webhook-certificates
          secret:
            secretName: strimzi-drain-cleaner
  strategy:
    type: RollingUpdate
