kind: Service
apiVersion: v1
metadata:
  name: strimzi-drain-cleaner
  labels:
    helm.sh/chart: strimzi-drain-cleaner-0.0.3
    app.kubernetes.io/name: strimzi-drain-cleaner
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.3.1"
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 8080
    - port: 443
      name: https
      protocol: TCP
      targetPort: 8443
  selector:
    app.kubernetes.io/name: strimzi-drain-cleaner
    app.kubernetes.io/instance: release-name
