apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: strimzi-drain-cleaner
  labels:
    helm.sh/chart: strimzi-drain-cleaner-0.0.3
    app.kubernetes.io/name: strimzi-drain-cleaner
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.3.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    cert-manager.io/inject-ca-from: strimzi-drain-cleaner/strimzi-drain-cleaner
webhooks:
  - name: strimzi-drain-cleaner.strimzi.io
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods/eviction"]
        scope: "Namespaced"
    clientConfig:
      service:
        namespace: strimzi-drain-cleaner
        name: "strimzi-drain-cleaner"
        path: /drainer
        port: 443
      caBundle: Cg==
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Ignore
    timeoutSeconds: 5
