jobs:
  - job: 'run_systemtest'
    displayName: "Run systemtests"
    strategy:
      matrix:
        ${{ each arch in parameters.architectures }}:
          ${{ arch }}:
            arch: ${{ arch }}
            image: 'Ubuntu-22.04'
            jdk_version: '17'
    pool:
      vmImage: $(image)
    timeoutInMinutes: 20
    steps:
      - template: '../steps/setup_java.yaml'
        parameters:
          JDK_VERSION: $(jdk_version)
      - template: '../steps/setup_docker.yaml'
      - template: '../steps/setup_minikube.yaml'
      - task: DownloadPipelineArtifact@2
        inputs:
          source: current
          artifact: Container-$(arch)
          path: $(System.DefaultWorkingDirectory)
      - bash: |
          eval $(minikube docker-env)
          DOCKER_ARCHITECTURE=$(arch) make docker_load
          make docker_tag
          make docker_push
        env:
          BUILD_TAG: latest-$(arch)
        displayName: 'Docker load & tag & push to local registries - $(arch)'
      - script: |
          echo "##vso[task.setvariable variable=docker_registry]$(kubectl get service registry -n kube-system -o=jsonpath='{.spec.clusterIP}'):80"
        displayName: "Set docker_registry to local registry in minikube"
        condition: eq(variables['docker_registry'], 'localhost:5000')
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: true
          goals: 'verify'
          options: '-B -Psystemtest'
        env:
          DOCKER_REGISTRY: registry.minikube
          DOCKER_ORG: strimzi
          DOCKER_TAG: latest
        displayName: 'Run systemtests - $(arch) - Bundle installation'
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: true
          goals: 'verify'
          options: '-B -Psystemtest'
        env:
          DOCKER_REGISTRY: registry.minikube
          DOCKER_ORG: strimzi
          DOCKER_TAG: latest
          DC_INSTALL_TYPE: Helm
        displayName: 'Run systemtests - $(arch) - Helm installation'