jobs:
  - job: 'run_systemtest'
    displayName: "Run systemtests"
    strategy:
      matrix:
        'java-11':
          image: 'Ubuntu-18.04'
          jdk_version: '11'
          jdk_path: '/usr/lib/jvm/java-11-openjdk-amd64'
    pool:
      vmImage: $(image)
    timeoutInMinutes: 20
    steps:
      - template: '../steps/setup_java.yaml'
        parameters:
          JDK_PATH: $(jdk_path)
          JDK_VERSION: $(jdk_version)
      - template: '../steps/setup_docker.yaml'
      - template: '../steps/setup_minikube.yaml'
      - task: DownloadPipelineArtifact@2
        inputs:
          source: current
          artifact: Container
          path: $(System.DefaultWorkingDirectory)
      - bash: |
          eval $(minikube docker-env)
          make docker_load
          make docker_tag
          make docker_push
        displayName: 'Docker load & tag & push to local registries'
      - script: |
          echo "##vso[task.setvariable variable=docker_registry]$(kubectl get service registry -n kube-system -o=jsonpath='{.spec.clusterIP}'):80"
        displayName: "Set docker_registry to local registry in minikube"
        condition: eq(variables['docker_registry'], 'localhost:5000')
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: true
          goals: 'verify'
          options: '-B -Psystemtest'
        env:
          DOCKER_REGISTRY: registry.minikube
          DOCKER_ORG: strimzi
          DOCKER_TAG: latest
        displayName: 'Run systemtests'