apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: strimzi-drain-cleaner
  labels:
    app: strimzi-drain-cleaner
rules:
  # Drain Cleaner needs to be able to get the Kafka or ZooKeeper pods that are being evicted and patch them with the
  # annotation which tells Strimzi Cluster Operator to roll the Pod
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - patch
