# Triggers
trigger:
  branches:
    include:
      - 'main'
      - 'release-*'
pr:
  autoCancel: true
  branches:
    include:
      - '*'

# Stages
stages:
  - stage: java_build
    displayName: Java build
    jobs:
      - template: 'templates/jobs/build_java.yaml'
  - stage: container_build
    displayName: Prepare Container
    dependsOn:
      - java_build
    jobs:
      - template: 'templates/jobs/build_container.yaml'
        parameters:
          artifactSource: 'current'
          artifactProject: 'strimzi'
          artifactPipeline: ''
          artifactRunVersion: ''
          artifactRunId: ''
          architectures: ['amd64', 'arm64', 's390x', 'ppc64le']
  - stage: run_systemtests
    displayName: Run System-tests
    dependsOn:
      - container_build
    condition: succeeded()
    variables:
      docker_org: strimzi
      docker_registry: localhost:5000
    jobs:
      - template: 'templates/jobs/run_systemtests.yaml'
        parameters:
          # The system tests should currently always run only amd64 on Azure since we do not have any other environments
          # available. So when adding support for a new platform, you should not add it here unless you also add the
          # system tests support for it.
          architectures: ['amd64']
  - stage: container_publish
    displayName: Publish Container
    dependsOn:
      - container_build
      - run_systemtests
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
    jobs:
      - template: 'templates/jobs/push_container.yaml'
        parameters:
          dockerTag: 'latest'
          artifactSource: 'current'
          artifactProject: 'strimzi'
          artifactPipeline: ''
          artifactRunVersion: ''
          artifactRunId: ''
          architectures: ['amd64', 'arm64', 's390x', 'ppc64le']
