# Triggers
trigger: none
pr: none

# Parameters
parameters:
- name: releaseVersion
  displayName: Release Version
  type: string
- name: useSuffix
  displayName: Build suffixed images
  type: boolean
  default: true
- name: releaseSuffix
  displayName: Release Suffix
  type: number
- name: sourcePipelineId
  displayName: Pipeline ID of the source build
  type: number
  default: 36
  values:
  - 36
- name: sourceBuildId
  displayName: Build ID of the source build
  type: number

# Stages
stages:
  - stage: container_build
    displayName: Prepare Container
    jobs:
      - template: 'templates/jobs/build_container.yaml'
        parameters:
          artifactSource: 'specific'
          artifactProject: 'strimzi'
          artifactPipeline: '${{ parameters.sourcePipelineId }}'
          artifactRunVersion: 'specific'
          artifactRunId: '${{ parameters.sourceBuildId }}'
          architectures: ['amd64', 'arm64', 's390x', 'ppc64le']
  - stage: run_systemtests
    displayName: Run System-tests
    dependsOn:
      - container_build
    condition: succeeded()
    variables:
      docker_org: strimzi
      docker_registry: localhost:5000
    jobs:
      - template: 'templates/jobs/run_systemtests.yaml'
        parameters:
          # The system tests should currently always run only amd64 on Azure since we do not have any other environments
          # available. So when adding support for a new platform, you should not add it here unless you also add the
          # system tests support for it.
          architectures: [ 'amd64' ]
  - stage: containers_publish_with_suffix
    displayName: Publish Containers for ${{ parameters.releaseVersion }}-${{ parameters.releaseSuffix }}
    dependsOn: 
      - run_systemtests
    condition: and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/heads/release-'))
    jobs:
      - template: 'templates/jobs/push_container.yaml'
        parameters:
          dockerTag: '${{ parameters.releaseVersion }}-${{ parameters.releaseSuffix }}'
          artifactSource: 'current'
          artifactProject: 'strimzi'
          artifactPipeline: ''
          artifactRunVersion: ''
          artifactRunId: ''
          architectures: ['amd64', 'arm64', 's390x', 'ppc64le']
  - stage: manual_validation
    displayName: Validate container before pushing container as ${{ parameters.releaseVersion }}
    dependsOn: 
      - run_systemtests
      - containers_publish_with_suffix
    condition: and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/heads/release-'))
    jobs:
      - job: waitForValidation
        displayName: Wait for container image validation
        pool: server
        timeoutInMinutes: 4320 # job times out in 3 days
        steps:
        - task: ManualValidation@0
          timeoutInMinutes: 4310 # task times out in 1 day
          inputs:
            notifyUsers: |
              github@scholzj.com
              xstejs24@gmail.com
            instructions: 'Please validate the container image'
            onTimeout: 'reject'
  - stage: containers_publish
    displayName: Publish Containers for ${{ parameters.releaseVersion }}
    dependsOn:
      - manual_validation
      - run_systemtests
      - containers_publish_with_suffix
    condition: and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/heads/release-'))
    jobs:
      - template: 'templates/jobs/push_container.yaml'
        parameters:
          dockerTag: '${{ parameters.releaseVersion }}'
          artifactSource: 'current'
          artifactProject: 'strimzi'
          artifactPipeline: ''
          artifactRunVersion: ''
          artifactRunId: ''
          architectures: ['amd64', 'arm64', 's390x', 'ppc64le']