# Triggers
trigger: none
pr: none

# Parameters
parameters:
- name: releaseVersion
  displayName: Release Version
  type: string
- name: useSuffix
  displayName: Build suffixed images
  type: boolean
  default: true
- name: releaseSuffix
  displayName: Release Suffix
  type: number
- name: sourcePipelineId
  displayName: Pipeline ID of the source build
  type: number
  default: 36
  values:
  - 36
- name: sourceBuildId
  displayName: Build ID of the source build
  type: number

# Stages
stages:
  - stage: release_artifacts
    displayName: Release artifacts for ${{ parameters.releaseVersion }}
    condition: startsWith(variables['build.sourceBranch'], 'refs/heads/release-')
    jobs:
      - job: 'release_artifacts'
        displayName: 'Release Artifacts'
        strategy:
          matrix:
            'java-11':
              image: 'Ubuntu-18.04'
              jdk_version: '11'
              jdk_path: '/usr/lib/jvm/java-11-openjdk-amd64'
        # Set timeout for jobs
        timeoutInMinutes: 60
        # Base system
        pool:
          vmImage: 'Ubuntu-18.04'
        # Pipeline steps
        steps:
          - template: 'templates/setup_java.yaml'
            parameters:
              JDK_PATH: $(jdk_path)
              JDK_VERSION: $(jdk_version)
          - bash: ".azure/scripts/release-artifacts.sh"
            env:
              BUILD_REASON: $(Build.Reason)
              BRANCH: $(Build.SourceBranch)
              RELEASE_VERSION: '${{ parameters.releaseVersion }}'
              MVN_ARGS: '-B'
            displayName: "Prepare release artifacts"
          - publish: $(System.DefaultWorkingDirectory)/strimzi-drain-cleaner-${{ parameters.releaseVersion }}.tar.gz
            artifact: ReleaseTarGzArchive
          - publish: $(System.DefaultWorkingDirectory)/strimzi-drain-cleaner-${{ parameters.releaseVersion }}.zip
            artifact: ReleaseZipArchive
  - stage: containers_publish_with_suffix
    displayName: Publish Containers for ${{ parameters.releaseVersion }}-${{ parameters.releaseSuffix }}
    dependsOn: 
      - release_artifacts
    condition: and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/heads/release-'))
    jobs:
      - job: 'container_build'
        displayName: 'Tag & Push'
        # Set timeout for jobs
        timeoutInMinutes: 60
        # Base system
        pool:
          vmImage: 'Ubuntu-18.04'
        # Pipeline steps
        steps:
          - template: 'templates/setup_docker.yaml'
          - task: DownloadPipelineArtifact@2
            inputs:
              source: specific
              artifact: Container
              path: $(System.DefaultWorkingDirectory)
              project: strimzi
              pipeline: '${{ parameters.sourcePipelineId }}'
              runVersion: specific
              runId: '${{ parameters.sourceBuildId }}'
          - ${{ if eq(parameters.useSuffix, true) }}:
            - bash: ".azure/scripts/release-containers.sh"
              env:
                BUILD_REASON: $(Build.Reason)
                BRANCH: $(Build.SourceBranch)
                DOCKER_USER: $(QUAY_USER)
                DOCKER_PASS: $(QUAY_PASS)
                DOCKER_REGISTRY: "quay.io"
                DOCKER_ORG: "strimzi"
                RELEASE_VERSION: '${{ parameters.releaseVersion }}-${{ parameters.releaseSuffix }}'
              displayName: "Tag & Push container"
  - stage: containers_publish
    displayName: Publish Containers for ${{ parameters.releaseVersion }}
    dependsOn: 
      - release_artifacts
      - containers_publish_with_suffix
    condition: and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/heads/release-'))
    jobs:
      - job: 'container_build'
        displayName: 'Tag & Push'
        # Set timeout for jobs
        timeoutInMinutes: 60
        # Base system
        pool:
          vmImage: 'Ubuntu-18.04'
        # Pipeline steps
        steps:
          - template: 'templates/setup_docker.yaml'
          - task: DownloadPipelineArtifact@2
            inputs:
              source: specific
              artifact: Container
              path: $(System.DefaultWorkingDirectory)
              project: strimzi
              pipeline: '${{ parameters.sourcePipelineId }}'
              runVersion: specific
              runId: '${{ parameters.sourceBuildId }}'
          - bash: ".azure/scripts/release-containers.sh"
            env:
              BUILD_REASON: $(Build.Reason)
              BRANCH: $(Build.SourceBranch)
              DOCKER_USER: $(QUAY_USER)
              DOCKER_PASS: $(QUAY_PASS)
              DOCKER_REGISTRY: "quay.io"
              DOCKER_ORG: "strimzi"
              RELEASE_VERSION: '${{ parameters.releaseVersion }}'
            displayName: "Tag & Push container"
