apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: strimzi-drain-cleaner
  labels:
    app.kubernetes.io/name: strimzi-drain-cleaner
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - patch
