apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: strimzi-drain-cleaner
  labels:
    app.kubernetes.io/name: strimzi-drain-cleaner
  namespace: strimzi-drain-cleaner
spec:
  selfSigned: {}
