{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "strimzi-drain-cleaner.serviceAccountName" . }}
  labels:
    {{- include "strimzi-drain-cleaner.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - patch
{{- end }}
