{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "strimzi-drain-cleaner.serviceAccountName" . }}
  labels:
    {{- include "strimzi-drain-cleaner.labels" . | nindent 4 }}
rules:
  # Drain Cleaner needs to be able to get the Kafka or ZooKeeper pods that are being evicted and patch them with the
  # annotation which tells Strimzi Cluster Operator to roll the Pod
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - patch
{{- end }}
