{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: strimzi-drain-cleaner
  labels:
    {{- include "strimzi-drain-cleaner.labels" . | nindent 4 }}
  namespace: {{ default .Release.Namespace .Values.namespace.name }}
type: kubernetes.io/tls
data:
  {{- with .Values.secret }}
  tls.crt: {{ .tls_crt }}
  tls.key: {{ .tls_key }}
  {{- end }}
{{- end }}
