apiVersion: v2
appVersion: 1.3.0
description: Utility which helps with moving the Apache Kafka pods deployed by Strimzi
  from Kubernetes nodes which are being drained.
home: https://strimzi.io/
icon: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/main/documentation/logo/strimzi_logo.png
name: strimzi-drain-cleaner
sources:
- https://github.com/strimzi/drain-cleaner
type: application
version: 1.3.0
