#
# Follow the README.md file to generate a Secret with the actual certificates
#
#kind: Secret
#apiVersion: v1
#metadata:
#  name: strimzi-drain-cleaner
#  labels:
#    app: strimzi-drain-cleaner
#  namespace: strimzi-drain-cleaner
#type: kubernetes.io/tls
#data:
#  tls.crt: Cg==
#  tls.key: Cg==
