{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "strimzi-drain-cleaner.serviceAccountName" . }}
  labels:
    {{- include "strimzi-drain-cleaner.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "strimzi-drain-cleaner.serviceAccountName" . }}
    namespace: {{ default .Release.Namespace .Values.namespace.name }}
roleRef:
  kind: ClusterRole
  name: {{ include "strimzi-drain-cleaner.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
