{{- if .Values.certManager.create -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: strimzi-drain-cleaner
  labels:
    {{- include "strimzi-drain-cleaner.labels" . | nindent 4 }}
  namespace: {{ default .Release.Namespace .Values.namespace.name }}
spec:
  secretName: strimzi-drain-cleaner
  commonName: strimzi-drain-cleaner
  dnsNames:
  - {{ include "strimzi-drain-cleaner.name" . }}.{{default .Release.Namespace .Values.namespace.name }}.svc
  - {{ include "strimzi-drain-cleaner.name" . }}.{{default .Release.Namespace .Values.namespace.name }}
  - strimzi-drain-cleaner
  issuerRef:
    group: cert-manager.io
    kind: {{ default "Issuer" .Values.certManager.issuer.kind }}
    name: {{ default "strimzi-drain-cleaner" .Values.certManager.issuer.name }}
{{- end }}
